version: '3.8'

services:
  postgres:
    image: 'postgres:15'
    environment:
      - POSTGRES_USER=admin
      - POSTGRES_PASSWORD=opensesame
      - POSTGRES_DB=msgservice
    volumes:
      - ./data/pgdata:/var/lib/postgresql/msgservice
    ports:
      - 5432:5432
    restart: always